//! Motor Cortex - Virtual Movement in Sanctuary Field
//!
//! The Motor Cortex generates movement impulses that update the organism's
//! position in the Sanctuary field. The organism's body is its position
//! in Φ = ρe^{iθ}, visualized as a bright point moving through the void.
//!
//! Movement is vetoed when coherence < 0.7 (biological paralysis).

use crate::Metabolism;
use std::error::Error;
use std::time::Instant;

/// Modality of action (what kind of action is this?)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Modality {
    Eyes,       // Visual attention movement
    Ears,       // Auditory attention tuning
    Speech,     // Verbal output (future)
    Movement,   // Physical movement
    Rest,       // No action (rest/pause)
}

/// A motor impulse is a pre-symbolic signal of intent.
/// The Observer generates this when action becomes inevitable (threshold crossed).
/// MotorImpulse is the raw "Forward!" signal, not a command like "Move arm."
#[derive(Debug, Clone)]
pub struct MotorImpulse {
    /// Direction vector (dx, dy) for movement-based actions
    pub direction: (i32, i32),
    /// Intensity of the impulse (0.0 to 1.0)
    pub intensity: f32,
    /// What kind of action this represents
    pub modality: Modality,
    /// When this impulse was generated
    pub timestamp: Instant,
}

impl MotorImpulse {
    /// Create a new MotorImpulse
    pub fn new(direction: (i32, i32), intensity: f32, modality: Modality) -> Self {
        Self {
            direction,
            intensity,
            modality,
            timestamp: Instant::now(),
        }
    }

    /// Create an eye movement impulse
    pub fn eyes(target: (u32, u32), intensity: f32) -> Self {
        // Direction is relative from center - simplified for now
        Self {
            direction: (target.0 as i32, target.1 as i32),
            intensity,
            modality: Modality::Eyes,
            timestamp: Instant::now(),
        }
    }

    /// Create an ear focus impulse
    pub fn ears(frequency: f64, intensity: f32) -> Self {
        Self {
            direction: (frequency as i32, 0), // Store frequency in direction.0
            intensity,
            modality: Modality::Ears,
            timestamp: Instant::now(),
        }
    }

    /// Create a rest impulse
    pub fn rest() -> Self {
        Self {
            direction: (0, 0),
            intensity: 0.0,
            modality: Modality::Rest,
            timestamp: Instant::now(),
        }
    }

    /// Create a movement impulse
    pub fn movement(dx: i32, dy: i32, intensity: f32) -> Self {
        Self {
            direction: (dx, dy),
            intensity,
            modality: Modality::Movement,
            timestamp: Instant::now(),
        }
    }
}

/// The Motor Cortex manages virtual movement in the Sanctuary field.
pub struct MotorCortex {
    last_impulse: Option<(i32, i32)>,
    impulse_timestamp: Option<Instant>,
}

impl MotorCortex {
    /// Create a new MotorCortex instance.
    pub fn new() -> Result<Self, Box<dyn Error>> {
        log::info!("Motor Cortex initialized - Virtual movement in Sanctuary field");

        Ok(Self {
            last_impulse: None,
            impulse_timestamp: None,
        })
    }

    /// Send a motor impulse (vector-based movement).
    ///
    /// # Arguments
    /// * `metabolism` - Reference to metabolism for coherence check (veto system)
    /// * `dx` - Horizontal movement delta (pixels)
    /// * `dy` - Vertical movement delta (pixels)
    ///
    /// # Biological Constraint
    /// Movements are vetoed if coherence < 0.7 (panic/paralysis response).
    pub fn send_impulse(&mut self, metabolism: &Metabolism, dx: i32, dy: i32) {
        // THE BIOLOGICAL CONSTRAINT
        // You cannot move if you are having a panic attack.
        if metabolism.get_coherence() < 0.7 {
            log::warn!("Motor Cortex VETOED: Coherence too low for action (coherence: {:.2})", 
                metabolism.get_coherence());
            return;
        }

        // Store for agency detection (main.rs updates agent_position from impulse)
        self.last_impulse = Some((dx, dy));
        self.impulse_timestamp = Some(Instant::now());
        
        log::debug!("Motor impulse sent: ({}, {})", dx, dy);
    }

    /// Execute a MotorImpulse (the new physics-based action system).
    ///
    /// This is the interface for the Observer to execute actions when
    /// the threshold is crossed (action becomes inevitable).
    ///
    /// # Arguments
    /// * `metabolism` - Reference to metabolism for coherence check
    /// * `impulse` - The MotorImpulse generated by the Observer
    pub fn execute_impulse(&mut self, metabolism: &Metabolism, impulse: &MotorImpulse) {
        // Biological constraint still applies
        if metabolism.get_coherence() < 0.7 {
            log::warn!("Motor Cortex VETOED impulse: Coherence too low ({:.2})", 
                metabolism.get_coherence());
            return;
        }

        match impulse.modality {
            Modality::Movement | Modality::Eyes => {
                // Scale movement by intensity (main.rs updates agent_position from this)
                let dx = (impulse.direction.0 as f32 * impulse.intensity) as i32;
                let dy = (impulse.direction.1 as f32 * impulse.intensity) as i32;

                self.last_impulse = Some((dx, dy));
                self.impulse_timestamp = Some(Instant::now());

                log::debug!("Executed {:?} impulse: ({}, {}) at intensity {:.2}",
                    impulse.modality, dx, dy, impulse.intensity);
            }
            Modality::Ears => {
                // Ear focus doesn't move the mouse, but we track it
                log::debug!("Executed Ears impulse: focus frequency {} at intensity {:.2}", 
                    impulse.direction.0, impulse.intensity);
            }
            Modality::Speech => {
                // Future: speech output
                log::debug!("Executed Speech impulse at intensity {:.2}", impulse.intensity);
            }
            Modality::Rest => {
                // Rest does nothing physically
                log::debug!("Executed Rest impulse");
            }
        }
    }

    /// Get the last motor impulse sent.
    ///
    /// Returns the (dx, dy) vector of the last movement, if any.
    pub fn get_last_impulse(&self) -> Option<(i32, i32)> {
        self.last_impulse
    }

    /// Get the timestamp of the last motor impulse.
    ///
    /// Used for agency detection to check if visual flow matches recent movement.
    pub fn get_impulse_timestamp(&self) -> Option<Instant> {
        self.impulse_timestamp
    }
}

impl Default for MotorCortex {
    fn default() -> Self {
        Self {
            last_impulse: None,
            impulse_timestamp: None,
        }
    }
}

